# Generated by Django 2.0.7 on 2020-03-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.CharField(default='https://lowbeeland.oss-cn-shanghai.aliyuncs.com/default.png', max_length=255, verbose_name='文章封面'),
        ),
    ]
